# Generated by Django 3.0 on 2019-12-17 02:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='카테고리 이름')),
            ],
            options={
                'verbose_name': '카테고리',
                'verbose_name_plural': '카테고리',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='상품 이름', max_length=64, verbose_name='상품 이름')),
                ('code', models.IntegerField(verbose_name='상품 코드')),
            ],
            options={
                'verbose_name': '상품',
                'verbose_name_plural': '상품',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_code', models.IntegerField(default=0, verbose_name='상품 코드')),
                ('article', models.TextField(verbose_name='질문 제목')),
                ('date', models.DateTimeField(verbose_name='등록 시간')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Category', verbose_name='카테고리')),
            ],
            options={
                'verbose_name': '질문',
                'verbose_name_plural': '질문',
            },
        ),
        migrations.CreateModel(
            name='Autoreply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_address', models.TextField(default='www.gogosing.com', verbose_name='url 주소')),
                ('auto_reply', models.TextField(default='답변 불가능한 항목입니다', verbose_name='자동 답변')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Question', verbose_name='질문')),
            ],
            options={
                'verbose_name': '자동답변',
                'verbose_name_plural': '자동답변',
            },
        ),
    ]
