# Generated by Django 2.2.3 on 2019-07-20 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='article',
            field=models.CharField(max_length=2000, verbose_name='질문 제목'),
        ),
    ]
