# Generated by Django 2.2.3 on 2019-07-27 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190720_2248'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='url_address',
            field=models.TextField(default='www.gogosing.com', verbose_name='url 주소'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(verbose_name='답변 내용'),
        ),
        migrations.AlterField(
            model_name='question',
            name='article',
            field=models.TextField(verbose_name='질문 제목'),
        ),
    ]
