# Generated by Django 2.2.3 on 2019-07-27 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20190727_1245'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='auto_reply',
            field=models.TextField(default='답변 불가능한 항목입니다', verbose_name='자동 답변'),
        ),
    ]
