# Generated by Django 2.2.3 on 2019-07-27 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_question_auto_reply'),
    ]

    operations = [
        migrations.CreateModel(
            name='Autoreply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_address', models.TextField(default='www.gogosing.com', verbose_name='url 주소')),
                ('auto_reply', models.TextField(default='답변 불가능한 항목입니다', verbose_name='자동 답변')),
            ],
            options={
                'verbose_name': '자동답변',
                'verbose_name_plural': '자동답변',
            },
        ),
        migrations.RemoveField(
            model_name='question',
            name='auto_reply',
        ),
        migrations.RemoveField(
            model_name='question',
            name='url_address',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.AddField(
            model_name='autoreply',
            name='question',
            field=models.ForeignKey(on_delete='CASCADE', to='core.Question', verbose_name='질문'),
        ),
    ]
