# Generated by Django 2.2.3 on 2019-07-29 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='name',
        ),
    ]
