# Generated by Django 2.2.3 on 2019-07-30 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20190730_1412'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='name',
            field=models.CharField(default='상품 이름', max_length=64, verbose_name='상품 이름'),
        ),
    ]
